// <auto-generated />
using ImobiliariaFacul.Banco;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImobiliariaFacul.Migrations
{
    [DbContext(typeof(ImobiliariaContext))]
    partial class ImobiliariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImobiliariaFacul.Modelos.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AreaTotal")
                        .HasColumnType("real");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Imoveis");

                    b.HasDiscriminator().HasValue("Imovel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ImobiliariaFacul.Modelos.Modelos.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ImobiliariaFacul.Modelos.Apto", b =>
                {
                    b.HasBaseType("ImobiliariaFacul.Modelos.Imovel");

                    b.Property<float>("AreaPrivativa")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Apto");
                });

            modelBuilder.Entity("ImobiliariaFacul.Modelos.Casa", b =>
                {
                    b.HasBaseType("ImobiliariaFacul.Modelos.Imovel");

                    b.Property<float>("AreaConstruida")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Casa");
                });

            modelBuilder.Entity("ImobiliariaFacul.Modelos.Terreno", b =>
                {
                    b.HasBaseType("ImobiliariaFacul.Modelos.Imovel");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Terreno");
                });
#pragma warning restore 612, 618
        }
    }
}
